#!/usr/bin/with-contenv bash

# create missing cache directory
mkdir -p /app/www/data/viewcache || :

# create symlinks
i=/app/www/data
[[ -e "$i" && ! -L "$i" && -e /config/"$(basename "$i")" ]] && \
    rm -Rf "$i" && \
    ln -s /config/"$(basename "$i")" "$i"
[[ -e "$i" && ! -L "$i" ]] && \
    mv "$i" /config/"$(basename "$i")" && \
    ln -s /config/"$(basename "$i")" "$i"

[[ -d /defaults/node_modules ]] && \
    mv /defaults/node_modules /app/www/public/node_modules

# check for config file and copy default if needed
[[ ! -f "/config/data/config.php" ]] && \
    cp /app/www/config-dist.php /config/data/config.php

[[ ! -f "/config/data/plugins/DemoBarcodeLookupPlugin.php" ]] && \
    cp -R /defaults/plugins /config/data

chown -R abc:abc \
    /app/www \
    /config
